version: '3'
services:
  db: 
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=homestead
      - MYSQL_ROOT_PASSWORD=root
